// Generated by CoffeeScript 1.8.0
(function() {
  window.onload = function() {
    document.getElementById('to').onclick = function() {
      var e, txt_str, yaml;
      txt_str = document.getElementById('txt').value;
      try {
        yaml = SurfacesTxt2Yaml.txt_to_yaml(txt_str, {
          compatible: 'ssp-lazy'
        });
      } catch (_error) {
        e = _error;
        alert(e);
      }
      return document.getElementById('yaml').value = yaml;
    };
    return document.getElementById('set_example').onclick = function() {
      var txt_str;
      txt_str = ajax.gets('examples/surfaces.txt');
      return document.getElementById('txt').value = txt_str;
    };
  };

}).call(this);
